name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check if it's a repository creation event
        run: |
          if [ "${{ github.event_name }}" == 'create' ]; then
            echo "Stopping job because it's a repository creation event."
            exit 0  # This will exit the script and stop the job
          fi

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}        
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test:coverage
